LSOADecileSQLData <- 
  tbl(DataSQLConnectionDM,
      in_schema("Demography",
                "Domains_Of_Deprivation_By_LSOA")) |>
  filter(`Effective_Snapshot_Date` == as.Date("2019-12-31")) |> 
  select(`LSOA` = `LSOA_Code`,
         `IMDDecile` = `IMD_Decile`) |> 
  collect()


# Clock Starts ------------------------------------------------------------
# Dataframe
RTTClockStartsSQLData <- 
  tbl(DataSQLConnectionDM,
      in_schema("COVID19",
                "National_Wait_List_Clock_Starts")) |> 
  filter(substr(`Derived_Registered_CCG`,
                1,
                3) == "11X" |
           substr(`NECS_Derived_Provider_Code_From_DLP`,
                  1,
                  3) %in% c("RH5",
                            "RA4")) |> 
  select(`StartDate` = `Referral_To_Treatment_Period_Start_Date`,
         `SnapshotDate` = `NECS_Derived_Week_Ending`,
         `CommissionerCode` = `Derived_Registered_CCG`,
         `ProviderCode` = `NECS_Derived_Provider_Code_From_DLP`,
         `LSOA` = `Derived_LSOA`) |> 
  collect() |> 
  mutate(`StartDate` = as.Date(`StartDate`),
         `SnapshotDate` = as.Date(`SnapshotDate`)) |> 
  mutate(`CommissionerCode` = case_when(`CommissionerCode` == "11X" ~ `CommissionerCode`,
                                        TRUE ~ "OTH"),
         `CommissionerDescription` = case_when(`CommissionerCode` == "11X" ~ "Somerset",
                                               TRUE ~ "Other"),
         `ProviderCode` = case_when(`ProviderCode` %in% c("RH5",
                                                          "RA4") ~ `ProviderCode`,
                                    TRUE ~ "OTH"),
         `ProviderDescription` = case_when(`ProviderCode` %in% c("RH5",
                                                                 "RBA",
                                                                 "RA4") ~ "Somerset",
                                           TRUE ~ "Other")) |>
  group_by(`StartDate`,
           `CommissionerCode`,
           `CommissionerDescription`,
           `ProviderCode`,
           `ProviderDescription`,
           `LSOA`) |> 
  summarise(`ClockStarts` = n()) |> 
  ungroup()


# Clock Stops -------------------------------------------------------------
# Dataframe
RTTClockStopsSQLData <- 
  tbl(DataSQLConnectionDM,
      in_schema("COVID19",
                "National_Wait_List_Clock_Stops")) |> 
  filter(substr(`Derived_Registered_CCG`,
                1,
                3) == "11X" |
           substr(`NECS_Derived_Provider_Code_From_DLP`,
                  1,
                  3) %in% c("RH5",
                            "RA4")) |> 
  select(`PseudoNHSNumber` = `Pseudo_NHS_Number`,
         `StartDate` = `Referral_To_Treatment_Period_Start_Date`,
         `SnapshotDate` = `NECS_Derived_Week_Ending`,
         `CommissionerCode` = `Derived_Registered_CCG`,
         `ProviderCode` = `NECS_Derived_Provider_Code_From_DLP`,
         `WaitingListCode` = `Waiting_List_Type`,
         `Age` = `Derived_Age_At_Activity`,
         `SexCode` = `Person_Stated_Gender_Code`,
         `EthnicityCode` = `Ethnic_Category`,
         `LSOA` = `Derived_LSOA`) |> 
  collect() |>
  mutate(`StartDate` = as.Date(`StartDate`),
         `SnapshotDate` = as.Date(`SnapshotDate`)) |> 
  mutate(`WaitDays` = difftime(`StartDate`,
                               `SnapshotDate`,
                               units = "days"),
         `WaitWeeks` = difftime(`StartDate`,
                                `SnapshotDate`,
                                units = "weeks")) |> 
  mutate(`MonthDate` = floor_date(as.Date(`StartDate`),
                                  "month"),
         `CommissionerCode` = case_when(`CommissionerCode` == "11X" ~ `CommissionerCode`,
                                        TRUE ~ "OTH"),
         `CommissionerDescription` = case_when(`CommissionerCode` == "11X" ~ "Somerset",
                                               TRUE ~ "Other"),
         `ProviderCode` = case_when(`ProviderCode` %in% c("RH5",
                                                          "RA4") ~ `ProviderCode`,
                                    TRUE ~ "OTH"),
         `ProviderDescription` = case_when(`ProviderCode` %in% c("RH5",
                                                                 "RBA",
                                                                 "RA4") ~ "Somerset",
                                           TRUE ~ "Other"),
         `WaitingListDescription` = case_when(`WaitingListCode` == "IRTT" ~ "Admitted",
                                              `WaitingListCode` == "ORTT" ~ "Non-admitted",
                                              TRUE ~ "Unknown"),
         `WaitWeeksGrouping` = case_when(`WaitWeeks` <= 51 ~ "0-51",
                                         `WaitWeeks` <= 64 ~ "52-64",
                                         `WaitWeeks` <= 77 ~ "65-77",
                                         `WaitWeeks` <= 103 ~ "78-103",
                                         `WaitWeeks` >= 104 ~ "104+"),
         `AgeGrouping` = case_when(`Age` >= 0 &
                                     `Age` <= 17 ~ "0-17",
                                   `Age` >= 18 &
                                     `Age` <= 64 ~ "18-64",
                                   `Age` >= 65 ~ "65+",
                                   TRUE ~ "Unknown"),
         `AgeBanding` = case_when(`Age` >= 0 &
                                    `Age` <= 4 ~ "0-4",
                                  `Age` >= 5 &
                                    `Age` <= 9 ~ "5-9",
                                  `Age` >= 10 &
                                    `Age` <= 14 ~ "10-14",
                                  `Age` >= 15 &
                                    `Age` <= 19 ~ "15-19",
                                  `Age` >= 20 &
                                    `Age` <= 24 ~ "20-24",
                                  `Age` >= 25 &
                                    `Age` <= 29 ~ "25-29",
                                  `Age` >= 30 &
                                    `Age` <= 34 ~ "30-34",
                                  `Age` >= 35 &
                                    `Age` <= 39 ~ "35-39",
                                  `Age` >= 40 &
                                    `Age` <= 44 ~ "40-44",
                                  `Age` >= 45 &
                                    `Age` <= 49 ~ "45-49",
                                  `Age` >= 50 &
                                    `Age` <= 54 ~ "50-54",
                                  `Age` >= 55 &
                                    `Age` <= 59 ~ "55-59",
                                  `Age` >= 60 &
                                    `Age` <= 64 ~ "60-64",
                                  `Age` >= 65 &
                                    `Age` <= 69 ~ "65-69",
                                  `Age` >= 70 &
                                    `Age` <= 74 ~ "70-74",
                                  `Age` >= 75 &
                                    `Age` <= 79 ~ "75-79",
                                  `Age` >= 80 &
                                    `Age` <= 84 ~ "80-84",
                                  `Age` >= 85 &
                                    `Age` <= 89 ~ "85-89",
                                  `Age` >= 90 &
                                    `Age` <= 94 ~ "90-94",
                                  `Age` >= 95 &
                                    `Age` <= 99 ~ "95-99",
                                  `Age` >= 100 ~ "100+",
                                  TRUE ~ "Unknown"),
         `SexDescription` = case_when(`SexCode` == "1" ~ "Male",
                                      `SexCode` == "2" ~ "Female",
                                      TRUE ~ "Other"),
         `EthnicityGroupDescription` = case_when(`EthnicityCode` %in% c("A",
                                                                        "B",
                                                                        "C") ~ "White",
                                                 `EthnicityCode` %in% c("D",
                                                                        "E",
                                                                        "F",
                                                                        "G") ~ "Mixed",
                                                 `EthnicityCode` %in% c("H",
                                                                        "J",
                                                                        "K",
                                                                        "L") ~ "Asian",
                                                 `EthnicityCode` %in% c("M",
                                                                        "N",
                                                                        "P") ~ "Black",
                                                 `EthnicityCode` %in% c("R",
                                                                        "S") ~ "Other",
                                                 `EthnicityCode` == "Z" ~ "Not stated",
                                                 TRUE ~ "Unknown"),
         `EthnicityDescription` = case_when(`EthnicityCode` == "A" ~ "British",
                                            `EthnicityCode` == "B" ~ "Irish",
                                            `EthnicityCode` == "C" ~ "Other",
                                            `EthnicityCode` == "D" ~ "White and Black Caribbean",
                                            `EthnicityCode` == "E" ~ "White and Black African",
                                            `EthnicityCode` == "F" ~ "White and Asian",
                                            `EthnicityCode` == "G" ~ "Other",
                                            `EthnicityCode` == "H" ~ "Indian",
                                            `EthnicityCode` == "J" ~ "Pakistani",
                                            `EthnicityCode` == "K" ~ "Bangladeshi",
                                            `EthnicityCode` == "L" ~ "Other",
                                            `EthnicityCode` == "M" ~ "Caribbean",
                                            `EthnicityCode` == "N" ~ "African",
                                            `EthnicityCode` == "P" ~ "Other",
                                            `EthnicityCode` == "R" ~ "Chinese",
                                            `EthnicityCode` == "S" ~ "Other",
                                            `EthnicityCode` == "Z" ~ "Not stated",
                                            TRUE ~ "Unknown")) |>
  group_by(`StartDate`,
           `CommissionerCode`,
           `CommissionerDescription`,
           `ProviderCode`,
           `ProviderDescription`,
           `WaitingListCode`,
           `WaitingListDescription`,
           `WaitWeeksGrouping`,
           `Age`,
           `AgeGrouping`,
           `AgeBanding`,
           `SexCode`,
           `SexDescription`,
           `EthnicityCode`,
           `EthnicityGroupDescription`,
           `EthnicityDescription`,
           `LSOA`) |> 
  summarise(`ClockStops` = n()) |> 
  ungroup()

# Open Pathways -----------------------------------------------------------
# Dataframe
RTTOpenPathwaysSQLData <- 
  tbl(DataSQLConnectionDM,
      in_schema("COVID19",
                "National_Wait_List_Open_Pathways")) |> 
  filter(substr(`Derived_Registered_CCG`,
                1,
                3) == "11X" |
           substr(`NECS_Derived_Provider_Code_From_DLP`,
                  1,
                  3) %in% c("RH5",
                            "RA4"),
         `Referral_Request_Received_Date` <= `NECS_Derived_Week_Ending`,
         `NECS_Derived_Week_Ending` == max(`NECS_Derived_Week_Ending`)) |> 
  select(`PseudoNHSNumber` = `Pseudo_NHS_Number`,
         `StartDate` = `Referral_To_Treatment_Period_Start_Date`,
         `SnapshotDate` = `NECS_Derived_Week_Ending`,
         `CommissionerCode` = `Derived_Registered_CCG`,
         `ProviderCode` = `NECS_Derived_Provider_Code_From_DLP`,
         `WaitingListCode` = `Waiting_List_Type`,
         `SpecialtyCode` = `Activity_Treatment_Function_Code`,
         `PriorityCode` = `Priority_Type_Code`,
         `ProcedurePriorityCode` = `Procedure_Priority_Code`,
         `TCIDate` = `TCI_Date`,
         `CancerPTL` = `Inclusion_On_Cancer_PTL`,
         `Age` = `Derived_Age_At_Activity`,
         `SexCode` = `Person_Stated_Gender_Code`,
         `EthnicityCode` = `Ethnic_Category`,
         `LSOA` = `Derived_LSOA`) |> 
  collect() |>
  mutate(`StartDate` = as.Date(`StartDate`),
         `SnapshotDate` = as.Date(`SnapshotDate`)) |> 
  left_join(LSOADecileSQLData,
            by = c("LSOA" = "LSOA")) |> 
  select(`PseudoNHSNumber`,
         `StartDate`,
         `SnapshotDate`,
         `CommissionerCode`,
         `ProviderCode`,
         `WaitingListCode`,
         `SpecialtyCode`,
         `PriorityCode`,
         `ProcedurePriorityCode`,
         `TCIDate`,
         `CancerPTL`,
         `Age`,
         `SexCode`,
         `EthnicityCode`,
         `LSOA`,
         `IMDDecile`) |> 
  mutate(`WaitDays` = interval(`StartDate`,
                               `SnapshotDate`) %/% days(1),
         `WaitWeeks` = interval(`StartDate`,
                                `SnapshotDate`) %/% days(7)) |> 
  mutate(`MonthDate` = floor_date(as.Date(`StartDate`),
                                  "month"),
         `CommissionerCode` = case_when(`CommissionerCode` == "11X" ~ `CommissionerCode`,
                                        TRUE ~ "OTH"),
         `CommissionerDescription` = case_when(`CommissionerCode` == "11X" ~ "Somerset",
                                               TRUE ~ "Other"),
         `ProviderCode` = case_when(`ProviderCode` %in% c("RH5",
                                                          "RA4") ~ `ProviderCode`,
                                    TRUE ~ "OTH"),
         `ProviderDescription` = case_when(`ProviderCode` %in% c("RH5",
                                                                 "RBA",
                                                                 "RA4") ~ "Somerset",
                                           TRUE ~ "Other"),
         `WaitingListDescription` = case_when(`WaitingListCode` == "IRTT" ~ "Admitted",
                                              `WaitingListCode` == "ORTT" ~ "Non-admitted",
                                              TRUE ~ "Unknown"),
         `WaitWeeksGrouping` = case_when(`WaitWeeks` <= 51 ~ "0-51",
                                         `WaitWeeks` <= 64 ~ "52-64",
                                         `WaitWeeks` <= 77 ~ "65-77",
                                         `WaitWeeks` <= 103 ~ "78-103",
                                         `WaitWeeks` >= 104 ~ "104+"),
         `SpecialtyDescription` = case_when(`SpecialtyCode` == "100" ~ "General Surgery",
                                            `SpecialtyCode` == "101" ~ "Urology",
                                            `SpecialtyCode` == "102" ~ "Transplant Surgery",
                                            `SpecialtyCode` == "103" ~ "Breast Surgery",
                                            `SpecialtyCode` == "104" ~ "Colorectal Surgery",
                                            `SpecialtyCode` == "105" ~ "Hepatobiliary and Pancreatic Surgery", 
                                            `SpecialtyCode` == "106" ~ "Upper Gastrointestinal Surgery",
                                            `SpecialtyCode` == "107" ~ "Vascular Surgery",
                                            `SpecialtyCode` == "108" ~ "Spinal Surgery",
                                            `SpecialtyCode` == "109" ~ "Bariatric Surgery",
                                            `SpecialtyCode` == "110" ~ "Trauma and Orthopaedic",
                                            `SpecialtyCode` == "111" ~ "Orthopaedic",
                                            `SpecialtyCode` == "113" ~ "Endocrine Surgery",
                                            `SpecialtyCode` == "115" ~ "Trauma Surgery",
                                            `SpecialtyCode` == "120" ~ "Ear, Nose, and Throat",
                                            `SpecialtyCode` == "130" ~ "Ophthalmology", 
                                            `SpecialtyCode` == "140" ~ "Oral Surgery",
                                            `SpecialtyCode` == "141" ~ "Restorative Dentistry",
                                            `SpecialtyCode` == "143" ~ "Orthodontic",
                                            `SpecialtyCode` == "144" ~ "Maxillofacial Surgery",
                                            `SpecialtyCode` == "145" ~ "Oral and Maxillofacial Surgery",
                                            `SpecialtyCode` == "150" ~ "Neurosurgical",
                                            `SpecialtyCode` == "160" ~ "Plastic Surgery",
                                            `SpecialtyCode` == "161" ~ "Burns Care",
                                            `SpecialtyCode` == "170" ~ "Cardiothoracic Surgery",
                                            `SpecialtyCode` == "172" ~ "Cardiac Surgery",
                                            `SpecialtyCode` == "173" ~ "Thoracic Surgery",
                                            `SpecialtyCode` == "174" ~ "Cardiothoracic Transplantation",
                                            `SpecialtyCode` == "191" ~ "Pain Management", 
                                            `SpecialtyCode` == "142" ~ "Paediatric Dentistry",
                                            `SpecialtyCode` == "171" ~ "Paediatric Surgery",
                                            `SpecialtyCode` == "211" ~ "Paediatric Urology",
                                            `SpecialtyCode` == "212" ~ "Paediatric Transplantation Surgery",
                                            `SpecialtyCode` == "213" ~ "Paediatric Gastrointestinal Surgery",
                                            `SpecialtyCode` == "214" ~ "Paediatric Trauma and Orthopaedic",
                                            `SpecialtyCode` == "215" ~ "Paediatric Ear, Nose, and Throat",
                                            `SpecialtyCode` == "216" ~ "Paediatric Ophthalmology",
                                            `SpecialtyCode` == "217" ~ "Paediatric Oral and Maxillofacial Surgery",
                                            `SpecialtyCode` == "218" ~ "Paediatric Neurosurgery",
                                            `SpecialtyCode` == "219" ~ "Paediatric Plastic Surgery",
                                            `SpecialtyCode` == "220" ~ "Paediatric Burns Care",
                                            `SpecialtyCode` == "221" ~ "Paediatric Cardiac Surgery",
                                            `SpecialtyCode` == "222" ~ "Paediatric Thoracic Surgery",
                                            `SpecialtyCode` == "223" ~ "Paediatric Epilepsy",
                                            `SpecialtyCode` == "230" ~ "Paediatric Clinical Pharmacology", 
                                            `SpecialtyCode` == "240" ~ "Paediatric Palliative Medicine",
                                            `SpecialtyCode` == "241" ~ "Paediatric Pain Management",
                                            `SpecialtyCode` == "242" ~ "Paediatric Intensive Care",
                                            `SpecialtyCode` == "250" ~ "Paediatric Hepatology",
                                            `SpecialtyCode` == "251" ~ "Paediatric Gastroenterology",
                                            `SpecialtyCode` == "252" ~ "Paediatric Endocrinology",
                                            `SpecialtyCode` == "253" ~ "Paediatric Clinical Haematology",
                                            `SpecialtyCode` == "254" ~ "Paediatric Audio Vestibular Medicine",
                                            `SpecialtyCode` == "255" ~ "Paediatric Clinical Immunology and Allergy",
                                            `SpecialtyCode` == "256" ~ "Paediatric Infectious Diseases",
                                            `SpecialtyCode` == "257" ~ "Paediatric Dermatology",
                                            `SpecialtyCode` == "258" ~ "Paediatric Respiratory Medicine",
                                            `SpecialtyCode` == "259" ~ "Paediatric Nephrology",
                                            `SpecialtyCode` == "260" ~ "Paediatric Medical Oncology",
                                            `SpecialtyCode` == "261" ~ "Paediatric Inherited Metabolic Medicine",
                                            `SpecialtyCode` == "262" ~ "Paediatric Rheumatology",
                                            `SpecialtyCode` == "263" ~ "Paediatric Diabetes",
                                            `SpecialtyCode` == "264" ~ "Paediatric Cystic Fibrosis",
                                            `SpecialtyCode` == "270" ~ "Paediatric Emergency Medicine",
                                            `SpecialtyCode` == "280" ~ "Paediatric Interventional Radiology",
                                            `SpecialtyCode` == "290" ~ "Community Paediatric",
                                            `SpecialtyCode` == "291" ~ "Paediatric Neurodisability",
                                            `SpecialtyCode` == "321" ~ "Paediatric Cardiology",
                                            `SpecialtyCode` == "421" ~ "Paediatric Neurology", 
                                            `SpecialtyCode` == "180" ~ "Emergency Medicine",
                                            `SpecialtyCode` == "190" ~ "Anaesthetic",
                                            `SpecialtyCode` == "192" ~ "Intensive Care Medicine",
                                            `SpecialtyCode` == "200" ~ "Aviation and Space Medicine",
                                            `SpecialtyCode` == "300" ~ "General Internal Medicine",
                                            `SpecialtyCode` == "301" ~ "Gastroenterology",
                                            `SpecialtyCode` == "302" ~ "Endocrinology",
                                            `SpecialtyCode` == "303" ~ "Clinical Haematology",
                                            `SpecialtyCode` == "304" ~ "Clinical Physiology",
                                            `SpecialtyCode` == "305" ~ "Clinical Pharmacology",
                                            `SpecialtyCode` == "306" ~ "Hepatology",
                                            `SpecialtyCode` == "307" ~ "Diabetes",
                                            `SpecialtyCode` == "308" ~ "Blood and Marrow Transplantation",
                                            `SpecialtyCode` == "309" ~ "Haemophilia",
                                            `SpecialtyCode` == "310" ~ "Audio Vestibular Medicine",
                                            `SpecialtyCode` == "311" ~ "Clinical Genetics",
                                            `SpecialtyCode` == "313" ~ "Clinical Immunology and Allergy", 
                                            `SpecialtyCode` == "314" ~ "Rehabilitation Medicine",
                                            `SpecialtyCode` == "315" ~ "Palliative Medicine",
                                            `SpecialtyCode` == "316" ~ "Clinical Immunology",
                                            `SpecialtyCode` == "317" ~ "Allergy",
                                            `SpecialtyCode` == "318" ~ "Intermediate Care",
                                            `SpecialtyCode` == "319" ~ "Respite Care",
                                            `SpecialtyCode` == "320" ~ "Cardiology",
                                            `SpecialtyCode` == "322" ~ "Clinical Microbiology",
                                            `SpecialtyCode` == "323" ~ "Spinal Injuries",
                                            `SpecialtyCode` == "324" ~ "Anticoagulant",
                                            `SpecialtyCode` == "325" ~ "Sport and Exercise Medicine",
                                            `SpecialtyCode` == "326" ~ "Acute Internal Medicine",
                                            `SpecialtyCode` == "327" ~ "Cardiac Rehabilitation",
                                            `SpecialtyCode` == "328" ~ "Stroke Medicine",
                                            `SpecialtyCode` == "329" ~ "Transient Ischaemic Attack",
                                            `SpecialtyCode` == "330" ~ "Dermatology",
                                            `SpecialtyCode` == "331" ~ "Congenital Heart Disease",
                                            `SpecialtyCode` == "333" ~ "Rare Disease",
                                            `SpecialtyCode` == "335" ~ "Inherited Metabolic Medicine",
                                            `SpecialtyCode` == "340" ~ "Respiratory Medicine",
                                            `SpecialtyCode` == "341" ~ "Respiratory Physiology",
                                            `SpecialtyCode` == "342" ~ "Pulmonary Rehabilitation",
                                            `SpecialtyCode` == "343" ~ "Adult Cystic Fibrosis",
                                            `SpecialtyCode` == "344" ~ "Complex Specialised Rehabilitation",
                                            `SpecialtyCode` == "345" ~ "Specialist Rehabilitation",
                                            `SpecialtyCode` == "346" ~ "Local Specialist Rehabilitation",
                                            `SpecialtyCode` == "347" ~ "Sleep Medicine",
                                            `SpecialtyCode` == "348" ~ "Post-COVID-19 Syndrome",
                                            `SpecialtyCode` == "350" ~ "Infectious Diseases",
                                            `SpecialtyCode` == "352" ~ "Tropical Medicine",
                                            `SpecialtyCode` == "360" ~ "Genitourinary Medicine",
                                            `SpecialtyCode` == "361" ~ "Renal Medicine",
                                            `SpecialtyCode` == "370" ~ "Medical Oncology",
                                            `SpecialtyCode` == "371" ~ "Nuclear Medicine",
                                            `SpecialtyCode` == "400" ~ "Neurology",
                                            `SpecialtyCode` == "401" ~ "Clinical Neurophysiology",
                                            `SpecialtyCode` == "410" ~ "Rheumatology",
                                            `SpecialtyCode` == "420" ~ "Paediatric",
                                            `SpecialtyCode` == "422" ~ "Neonatal Critical Care",
                                            `SpecialtyCode` == "424" ~ "Well Baby",
                                            `SpecialtyCode` == "430" ~ "Elderly Medicine",
                                            `SpecialtyCode` == "431" ~ "Orthogeriatric Medicine",
                                            `SpecialtyCode` == "450" ~ "Dental Medicine",
                                            `SpecialtyCode` == "451" ~ "Special Care Dentistry",
                                            `SpecialtyCode` == "460" ~ "Medical Ophthalmology",
                                            `SpecialtyCode` == "461" ~ "Ophthalmic and Vision Science",
                                            `SpecialtyCode` == "501" ~ "Obstetrics",
                                            `SpecialtyCode` == "502" ~ "Gynaecology",
                                            `SpecialtyCode` == "503" ~ "Gynaecological Oncology",
                                            `SpecialtyCode` == "504" ~ "Community Sexual and Reproductive Health",
                                            `SpecialtyCode` == "505" ~ "Fetal Medicine",
                                            `SpecialtyCode` == "560" ~ "Midwifery",
                                            `SpecialtyCode` == "650" ~ "Physiotherapy",
                                            `SpecialtyCode` == "651" ~ "Occupational Therapy",
                                            `SpecialtyCode` == "652" ~ "Speech and Language Therapy",
                                            `SpecialtyCode` == "653" ~ "Podiatry",
                                            `SpecialtyCode` == "654" ~ "Dietetics",
                                            `SpecialtyCode` == "655" ~ "Orthoptics",
                                            `SpecialtyCode` == "656" ~ "Clinical Psychology",
                                            `SpecialtyCode` == "657" ~ "Prosthetics",
                                            `SpecialtyCode` == "658" ~ "Orthotics",
                                            `SpecialtyCode` == "659" ~ "Dramatherapy",
                                            `SpecialtyCode` == "660" ~ "Art Therapy",
                                            `SpecialtyCode` == "661" ~ "Music Therapy",
                                            `SpecialtyCode` == "662" ~ "Optometry",
                                            `SpecialtyCode` == "663" ~ "Podiatric Surgery",
                                            `SpecialtyCode` == "670" ~ "Urological Physiology",
                                            `SpecialtyCode` == "673" ~ "Vascular Physiology",
                                            `SpecialtyCode` == "675" ~ "Cardiac Physiology",
                                            `SpecialtyCode` == "677" ~ "Gastrointestinal Physiology",
                                            `SpecialtyCode` == "700" ~ "Learning Disability",
                                            `SpecialtyCode` == "710" ~ "Adult Mental Health",
                                            `SpecialtyCode` == "711" ~ "Child and Adolescent Psychiatry",
                                            `SpecialtyCode` == "712" ~ "Forensic Psychiatry",
                                            `SpecialtyCode` == "713" ~ "Medical Psychotherapy",
                                            `SpecialtyCode` == "715" ~ "Old Age Psychiatry",
                                            `SpecialtyCode` == "720" ~ "Eating Disorders",
                                            `SpecialtyCode` == "721" ~ "Addiction",
                                            `SpecialtyCode` == "722" ~ "Liaison Psychiatry",
                                            `SpecialtyCode` == "723" ~ "Psychiatric Intensive Care",
                                            `SpecialtyCode` == "724" ~ "Perinatal Mental Health",
                                            `SpecialtyCode` == "725" ~ "Mental Health Recovery and Rehabilitation",
                                            `SpecialtyCode` == "726" ~ "Mental Health Dual Diagnosis",
                                            `SpecialtyCode` == "727" ~ "Dementia Assessment",
                                            `SpecialtyCode` == "730" ~ "Neuropsychiatry",
                                            `SpecialtyCode` == "800" ~ "Clinical Oncology",
                                            `SpecialtyCode` == "811" ~ "Interventional Radiology",
                                            `SpecialtyCode` == "812" ~ "Diagnostic Imaging",
                                            `SpecialtyCode` == "822" ~ "Chemical Pathology",
                                            `SpecialtyCode` == "834" ~ "Medical Virology",
                                            `SpecialtyCode` == "840" ~ "Audiology",
                                            `SpecialtyCode` == "920" ~ "Diabetic Education",
                                            TRUE ~ "Unknown"),
         `PriorityDescription` = case_when(`PriorityCode` == "1" ~ "Routine",
                                           `PriorityCode` == "2" ~ "Urgent",
                                           `PriorityCode` == "3" ~ "Two week wait",
                                           TRUE ~ "Unknown"),
         `ProcedurePriorityDescription` = case_when(`ProcedurePriorityCode` == "P2" ~ "<1 month",
                                                    `ProcedurePriorityCode` == "P3" ~ "<3 months",
                                                    `ProcedurePriorityCode` == "P4" ~ ">3 months",
                                                    `ProcedurePriorityCode` == "P5" ~ "Postpone (COVID-19)",
                                                    `ProcedurePriorityCode` == "P6" ~ "Postpone (non-COVID-19)",
                                                    TRUE ~ "Unknown"),
         `TCIDateFlag` = case_when(!is_null(`TCIDate`) ~ "Y",
                                   TRUE ~ "N"),
         `CancerPTLFlag` = case_when(`CancerPTL` %in% c("Y",
                                                        "Yes") ~ "Y",
                                     `CancerPTL` %in% c("N",
                                                        "No") ~ "N",
                                     TRUE ~ "U"),
         `AgeGrouping` = case_when(`Age` >= 0 &
                                     `Age` <= 17 ~ "0-17",
                                   `Age` >= 18 &
                                     `Age` <= 64 ~ "18-64",
                                   `Age` >= 65 ~ "65+",
                                   TRUE ~ "Unknown"),
         `AgeBanding` = case_when(`Age` >= 0 &
                                    `Age` <= 4 ~ "0-4",
                                  `Age` >= 5 &
                                    `Age` <= 9 ~ "5-9",
                                  `Age` >= 10 &
                                    `Age` <= 14 ~ "10-14",
                                  `Age` >= 15 &
                                    `Age` <= 19 ~ "15-19",
                                  `Age` >= 20 &
                                    `Age` <= 24 ~ "20-24",
                                  `Age` >= 25 &
                                    `Age` <= 29 ~ "25-29",
                                  `Age` >= 30 &
                                    `Age` <= 34 ~ "30-34",
                                  `Age` >= 35 &
                                    `Age` <= 39 ~ "35-39",
                                  `Age` >= 40 &
                                    `Age` <= 44 ~ "40-44",
                                  `Age` >= 45 &
                                    `Age` <= 49 ~ "45-49",
                                  `Age` >= 50 &
                                    `Age` <= 54 ~ "50-54",
                                  `Age` >= 55 &
                                    `Age` <= 59 ~ "55-59",
                                  `Age` >= 60 &
                                    `Age` <= 64 ~ "60-64",
                                  `Age` >= 65 &
                                    `Age` <= 69 ~ "65-69",
                                  `Age` >= 70 &
                                    `Age` <= 74 ~ "70-74",
                                  `Age` >= 75 &
                                    `Age` <= 79 ~ "75-79",
                                  `Age` >= 80 &
                                    `Age` <= 84 ~ "80-84",
                                  `Age` >= 85 &
                                    `Age` <= 89 ~ "85-89",
                                  `Age` >= 90 &
                                    `Age` <= 94 ~ "90-94",
                                  `Age` >= 95 &
                                    `Age` <= 99 ~ "95-99",
                                  `Age` >= 100 ~ "100+",
                                  TRUE ~ "Unknown"),
         `SexDescription` = case_when(`SexCode` == "1" ~ "Male",
                                      `SexCode` == "2" ~ "Female",
                                      TRUE ~ "Other"),
         `EthnicityGroupDescription` = case_when(`EthnicityCode` %in% c("A",
                                                                        "B",
                                                                        "C") ~ "White",
                                                 `EthnicityCode` %in% c("D",
                                                                        "E",
                                                                        "F",
                                                                        "G") ~ "Mixed",
                                                 `EthnicityCode` %in% c("H",
                                                                        "J",
                                                                        "K",
                                                                        "L") ~ "Asian",
                                                 `EthnicityCode` %in% c("M",
                                                                        "N",
                                                                        "P") ~ "Black",
                                                 `EthnicityCode` %in% c("R",
                                                                        "S") ~ "Other",
                                                 `EthnicityCode` == "Z" ~ "Not stated",
                                                 TRUE ~ "Unknown"),
         `EthnicityDescription` = case_when(`EthnicityCode` == "A" ~ "British",
                                            `EthnicityCode` == "B" ~ "Irish",
                                            `EthnicityCode` == "C" ~ "Other",
                                            `EthnicityCode` == "D" ~ "White and Black Caribbean",
                                            `EthnicityCode` == "E" ~ "White and Black African",
                                            `EthnicityCode` == "F" ~ "White and Asian",
                                            `EthnicityCode` == "G" ~ "Other",
                                            `EthnicityCode` == "H" ~ "Indian",
                                            `EthnicityCode` == "J" ~ "Pakistani",
                                            `EthnicityCode` == "K" ~ "Bangladeshi",
                                            `EthnicityCode` == "L" ~ "Other",
                                            `EthnicityCode` == "M" ~ "Caribbean",
                                            `EthnicityCode` == "N" ~ "African",
                                            `EthnicityCode` == "P" ~ "Other",
                                            `EthnicityCode` == "R" ~ "Chinese",
                                            `EthnicityCode` == "S" ~ "Other",
                                            `EthnicityCode` == "Z" ~ "Not stated",
                                            TRUE ~ "Unknown")) |>
  group_by(`PseudoNHSNumber`,
           `MonthDate`,
           `StartDate`,
           `SnapshotDate`,
           `CommissionerDescription`,
           `ProviderDescription`,
           `WaitingListDescription`,
           `WaitDays`,
           `WaitWeeks`,
           `WaitWeeksGrouping`,
           `SpecialtyDescription`,
           `PriorityDescription`,
           `ProcedurePriorityDescription`,
           `TCIDateFlag`,
           `CancerPTLFlag`,
           `AgeGrouping`,
           `AgeBanding`,
           `SexDescription`,
           `EthnicityGroupDescription`,
           `EthnicityDescription`,
           `LSOA`,
           `IMDDecile`) |> 
  summarise(`OpenPathways` = n()) |> 
  ungroup()

# Performance -------------------------------------------------------------
# Dataframe
RTTPerformanceSQLData <- 
  tbl(DataSQLConnectionDM,
      in_schema("Performance",
                "RTT_Data")) |> 
  filter(substr(`Commissioner_Organisation_Code`,
                1,
                3) == "11X" |
           substr(`Provider_Organisation_Code`,
                  1,
                  3) %in% c("RH5",
                            "RBA",
                            "RA4"),
         (`Data_Status` == "Public" |
            `Data_Status` == "Provisional" &
            `Report_Date` == EndMonthDate),
         `Treatment_Function_Code` != "C_999") |>
  collect() |> 
  mutate(`Report_Date` = as.Date(`Report_Date`)) |> 
  filter(`Report_Date` >= max(`Report_Date`) %m-% months(36)) |> 
  mutate(`Gt_00_To_00_Weeks` = case_when(`RTT_Part_Description` == "New RTT Periods - All Patients" ~ `Total_All`,
                                         TRUE ~ as.integer(NA))) |> 
  pivot_longer(cols = starts_with("Gt_"),
               names_to = "Week",
               values_to = "Waits") |> 
  mutate(`SpecialtyDescription` = case_when(`Treatment_Function_Code` == "C_100" ~ "General Surgery",
                                            `Treatment_Function_Code` == "C_101" ~ "Urology",
                                            `Treatment_Function_Code` == "C_110" ~ "Trauma and Orthopaedic",
                                            `Treatment_Function_Code` == "C_120" ~ "Ear, Nose, and Throat",
                                            `Treatment_Function_Code` == "C_130" ~ "Ophthalmology",
                                            `Treatment_Function_Code` == "C_140" ~ "Oral Surgery",
                                            `Treatment_Function_Code` == "C_150" ~ "Neurosurgical",
                                            `Treatment_Function_Code` == "C_160" ~ "Plastic Surgery",
                                            `Treatment_Function_Code` == "C_170" ~ "Cardiothoracic Surgery",
                                            `Treatment_Function_Code` == "C_300" ~ "General Internal Medicine",
                                            `Treatment_Function_Code` == "C_301" ~ "Gastroenterology",
                                            `Treatment_Function_Code` == "C_320" ~ "Cardiology",
                                            `Treatment_Function_Code` == "C_330" ~ "Dermatology",
                                            `Treatment_Function_Code` == "C_340" ~ "Respiratory Medicine",
                                            `Treatment_Function_Code` == "C_400" ~ "Neurology",
                                            `Treatment_Function_Code` == "C_410" ~ "Rheumatology",
                                            `Treatment_Function_Code` == "C_430" ~ "Elderly Medicine",
                                            `Treatment_Function_Code` == "C_502" ~ "Gynaecology",
                                            `Treatment_Function_Code` == "X01" ~ "Other",
                                            `Treatment_Function_Code` == "X02" ~ "Other - Medical",
                                            `Treatment_Function_Code` == "X03" ~ "Other - Mental Health",
                                            `Treatment_Function_Code` == "X04" ~ "Other - Paediatric",
                                            `Treatment_Function_Code` == "X05" ~ "Other - Surgical",
                                            `Treatment_Function_Code` == "X06" ~ "Other",
                                            TRUE ~ "Unknown"),
         `Week` = case_when(`Week` == "Gt_00_To_00_Weeks" ~ 0,
                            `Week` == "Gt_00_To_01_Weeks" ~ 0,
                            `Week` == "Gt_01_To_02_Weeks" ~ 1,
                            `Week` == "Gt_02_To_03_Weeks" ~ 2,
                            `Week` == "Gt_03_To_04_Weeks" ~ 3,
                            `Week` == "Gt_04_To_05_Weeks" ~ 4,
                            `Week` == "Gt_05_To_06_Weeks" ~ 5,
                            `Week` == "Gt_06_To_07_Weeks" ~ 6,
                            `Week` == "Gt_07_To_08_Weeks" ~ 7,
                            `Week` == "Gt_08_To_09_Weeks" ~ 8,
                            `Week` == "Gt_09_To_10_Weeks" ~ 9,
                            `Week` == "Gt_10_To_11_Weeks" ~ 10,
                            `Week` == "Gt_11_To_12_Weeks" ~ 11,
                            `Week` == "Gt_12_To_13_Weeks" ~ 12,
                            `Week` == "Gt_13_To_14_Weeks" ~ 13,
                            `Week` == "Gt_14_To_15_Weeks" ~ 14,
                            `Week` == "Gt_15_To_16_Weeks" ~ 15,
                            `Week` == "Gt_16_To_17_Weeks" ~ 16,
                            `Week` == "Gt_17_To_18_Weeks" ~ 17,
                            `Week` == "Gt_18_To_19_Weeks" ~ 18,
                            `Week` == "Gt_19_To_20_Weeks" ~ 19,
                            `Week` == "Gt_20_To_21_Weeks" ~ 20,
                            `Week` == "Gt_21_To_22_Weeks" ~ 21,
                            `Week` == "Gt_22_To_23_Weeks" ~ 22,
                            `Week` == "Gt_23_To_24_Weeks" ~ 23,
                            `Week` == "Gt_24_To_25_Weeks" ~ 24,
                            `Week` == "Gt_25_To_26_Weeks" ~ 25,
                            `Week` == "Gt_26_To_27_Weeks" ~ 26,
                            `Week` == "Gt_27_To_28_Weeks" ~ 27,
                            `Week` == "Gt_28_To_29_Weeks" ~ 28,
                            `Week` == "Gt_29_To_30_Weeks" ~ 29,
                            `Week` == "Gt_30_To_31_Weeks" ~ 30,
                            `Week` == "Gt_31_To_32_Weeks" ~ 31,
                            `Week` == "Gt_32_To_33_Weeks" ~ 32,
                            `Week` == "Gt_33_To_34_Weeks" ~ 33,
                            `Week` == "Gt_34_To_35_Weeks" ~ 34,
                            `Week` == "Gt_35_To_36_Weeks" ~ 35,
                            `Week` == "Gt_36_To_37_Weeks" ~ 36,
                            `Week` == "Gt_37_To_38_Weeks" ~ 37,
                            `Week` == "Gt_38_To_39_Weeks" ~ 38,
                            `Week` == "Gt_39_To_40_Weeks" ~ 39,
                            `Week` == "Gt_40_To_41_Weeks" ~ 40,
                            `Week` == "Gt_41_To_42_Weeks" ~ 41,
                            `Week` == "Gt_42_To_43_Weeks" ~ 42,
                            `Week` == "Gt_43_To_44_Weeks" ~ 43,
                            `Week` == "Gt_44_To_45_Weeks" ~ 44,
                            `Week` == "Gt_45_To_46_Weeks" ~ 45,
                            `Week` == "Gt_46_To_47_Weeks" ~ 46,
                            `Week` == "Gt_47_To_48_Weeks" ~ 47,
                            `Week` == "Gt_48_To_49_Weeks" ~ 48,
                            `Week` == "Gt_49_To_50_Weeks" ~ 49,
                            `Week` == "Gt_50_To_51_Weeks" ~ 50,
                            `Week` == "Gt_51_To_52_Weeks" ~ 51,
                            `Week` == "Gt_52_Weeks" ~ 52,
                            `Week` == "Gt_52_To_53_Weeks" ~ 52,
                            `Week` == "Gt_53_To_54_Weeks" ~ 53,
                            `Week` == "Gt_54_To_55_Weeks" ~ 54,
                            `Week` == "Gt_55_To_56_Weeks" ~ 55,
                            `Week` == "Gt_56_To_57_Weeks" ~ 56,
                            `Week` == "Gt_57_To_58_Weeks" ~ 57,
                            `Week` == "Gt_58_To_59_Weeks" ~ 58,
                            `Week` == "Gt_59_To_60_Weeks" ~ 59,
                            `Week` == "Gt_60_To_61_Weeks" ~ 60,
                            `Week` == "Gt_61_To_62_Weeks" ~ 61,
                            `Week` == "Gt_62_To_63_Weeks" ~ 62,
                            `Week` == "Gt_63_To_64_Weeks" ~ 63,
                            `Week` == "Gt_64_To_65_Weeks" ~ 64,
                            `Week` == "Gt_65_To_66_Weeks" ~ 65,
                            `Week` == "Gt_66_To_67_Weeks" ~ 66,
                            `Week` == "Gt_67_To_68_Weeks" ~ 67,
                            `Week` == "Gt_68_To_69_Weeks" ~ 68,
                            `Week` == "Gt_69_To_70_Weeks" ~ 69,
                            `Week` == "Gt_70_To_71_Weeks" ~ 70,
                            `Week` == "Gt_71_To_72_Weeks" ~ 71,
                            `Week` == "Gt_72_To_73_Weeks" ~ 72,
                            `Week` == "Gt_73_To_74_Weeks" ~ 73,
                            `Week` == "Gt_74_To_75_Weeks" ~ 74,
                            `Week` == "Gt_75_To_76_Weeks" ~ 75,
                            `Week` == "Gt_76_To_77_Weeks" ~ 76,
                            `Week` == "Gt_77_To_78_Weeks" ~ 77,
                            `Week` == "Gt_78_To_79_Weeks" ~ 78,
                            `Week` == "Gt_79_To_80_Weeks" ~ 79,
                            `Week` == "Gt_80_To_81_Weeks" ~ 80,
                            `Week` == "Gt_81_To_82_Weeks" ~ 81,
                            `Week` == "Gt_82_To_83_Weeks" ~ 82,
                            `Week` == "Gt_83_To_84_Weeks" ~ 83,
                            `Week` == "Gt_84_To_85_Weeks" ~ 84,
                            `Week` == "Gt_85_To_86_Weeks" ~ 85,
                            `Week` == "Gt_86_To_87_Weeks" ~ 86,
                            `Week` == "Gt_87_To_88_Weeks" ~ 87,
                            `Week` == "Gt_88_To_89_Weeks" ~ 88,
                            `Week` == "Gt_89_To_90_Weeks" ~ 89,
                            `Week` == "Gt_90_To_91_Weeks" ~ 90,
                            `Week` == "Gt_91_To_92_Weeks" ~ 91,
                            `Week` == "Gt_92_To_93_Weeks" ~ 92,
                            `Week` == "Gt_93_To_94_Weeks" ~ 93,
                            `Week` == "Gt_94_To_95_Weeks" ~ 94,
                            `Week` == "Gt_95_To_96_Weeks" ~ 95,
                            `Week` == "Gt_96_To_97_Weeks" ~ 96,
                            `Week` == "Gt_97_To_98_Weeks" ~ 97,
                            `Week` == "Gt_98_To_99_Weeks" ~ 98,
                            `Week` == "Gt_99_To_100_Weeks" ~ 99,
                            `Week` == "Gt_100_To_101_Weeks" ~ 100,
                            `Week` == "Gt_101_To_102_Weeks" ~ 101,
                            `Week` == "Gt_102_To_103_Weeks" ~ 102,
                            `Week` == "Gt_103_To_104_Weeks" ~ 103,
                            `Week` == "Gt_104_Weeks" ~ 104)) |> 
  select(`StartDate` = `Report_Date`,
         `CommissionerCode` = `Commissioner_Organisation_Code`,
         `ProviderCode` = `Provider_Organisation_Code`,
         `PathwayDescription` = `RTT_Part_Description`,
         `SpecialtyDescription`,
         `Week`,
         `Waits`) |> 
  mutate(`MonthDate` = floor_date(as.Date(`StartDate`),
                                  "month"),
         `CommissionerCode` = case_when(`CommissionerCode` == "11X" ~ `CommissionerCode`,
                                        TRUE ~ "OTH"),
         `CommissionerDescription` = case_when(`CommissionerCode` == "11X" ~ "Somerset",
                                               TRUE ~ "Other"),
         `ProviderCode` = case_when(`ProviderCode` %in% c("RH5",
                                                          "RBA",
                                                          "RA4") ~ `ProviderCode`,
                                    TRUE ~ "OTH"),
         `ProviderDescription` = case_when(`ProviderCode` %in% c("RH5",
                                                                 "RBA",
                                                                 "RA4") ~ "Somerset",
                                           TRUE ~ "Other"),
         `WeekGrouping1` = case_when(`Week` <= 17 ~ "0-17",
                                     `Week` >= 18 ~ "18+"),
         `WeekGrouping2` = case_when(`Week` <= 51 ~ "0-51",
                                     `Week` <= 64 ~ "52-64",
                                     `Week` <= 77 ~ "65-77",
                                     `Week` <= 103 ~ "78-103",
                                     `Week` >= 104 ~ "104+")) |> 
  group_by(`MonthDate`,
           `CommissionerDescription`,
           `ProviderCode`,
           `ProviderDescription`,
           `PathwayDescription`,
           `SpecialtyDescription`,
           `WeekGrouping1`,
           `WeekGrouping2`,
           `Week`) |> 
  summarise(`Waits` = sum(`Waits`,
                          na.rm = TRUE)) |> 
  ungroup()