
# Performance -------------------------------------------------------------
# Dataframe

RTTPerformanceSQLData_EndDate <- 
  tbl(DataSQLConnectionDM,
      in_schema("Performance",
                "RTT_Data")) %>% 
  select(Report_Date) %>% 
  distinct() %>% 
  collect %>% 
  filter(Report_Date == max(Report_Date)) %>% 
  pull()
  


RTTPerformanceSQLData <- 
  tbl(DataSQLConnectionDM,
      in_schema("Performance",
                "RTT_Data")) |> 
  filter(substr(`Commissioner_Organisation_Code`,
                1,
                3) == "11X" |
           substr(`Provider_Organisation_Code`,
                  1,
                  3) %in% c("RH5",
                            "RBA",
                            "RA4"),
         (`Data_Status` == "Public" |
            `Data_Status` == "Provisional" &
            `Report_Date` == RTTPerformanceSQLData_EndDate),
         `Treatment_Function_Code` != "C_999",
         RTT_Part_Description == "Incomplete Pathways",
         Report_Date >= "2021-04-01") |>
  collect() |> 
  mutate(`Report_Date` = as.Date(`Report_Date`)) |> 
  mutate(`Gt_00_To_00_Weeks` = case_when(`RTT_Part_Description` == "New RTT Periods - All Patients" ~ `Total_All`,
                                         TRUE ~ as.integer(NA))) |> 
  pivot_longer(cols = starts_with("Gt_"),
               names_to = "Week",
               values_to = "Waits") |> 
  mutate(
         `Week` = case_when(`Week` == "Gt_00_To_00_Weeks" ~ 0,
                            `Week` == "Gt_00_To_01_Weeks" ~ 0,
                            `Week` == "Gt_01_To_02_Weeks" ~ 1,
                            `Week` == "Gt_02_To_03_Weeks" ~ 2,
                            `Week` == "Gt_03_To_04_Weeks" ~ 3,
                            `Week` == "Gt_04_To_05_Weeks" ~ 4,
                            `Week` == "Gt_05_To_06_Weeks" ~ 5,
                            `Week` == "Gt_06_To_07_Weeks" ~ 6,
                            `Week` == "Gt_07_To_08_Weeks" ~ 7,
                            `Week` == "Gt_08_To_09_Weeks" ~ 8,
                            `Week` == "Gt_09_To_10_Weeks" ~ 9,
                            `Week` == "Gt_10_To_11_Weeks" ~ 10,
                            `Week` == "Gt_11_To_12_Weeks" ~ 11,
                            `Week` == "Gt_12_To_13_Weeks" ~ 12,
                            `Week` == "Gt_13_To_14_Weeks" ~ 13,
                            `Week` == "Gt_14_To_15_Weeks" ~ 14,
                            `Week` == "Gt_15_To_16_Weeks" ~ 15,
                            `Week` == "Gt_16_To_17_Weeks" ~ 16,
                            `Week` == "Gt_17_To_18_Weeks" ~ 17,
                            `Week` == "Gt_18_To_19_Weeks" ~ 18,
                            `Week` == "Gt_19_To_20_Weeks" ~ 19,
                            `Week` == "Gt_20_To_21_Weeks" ~ 20,
                            `Week` == "Gt_21_To_22_Weeks" ~ 21,
                            `Week` == "Gt_22_To_23_Weeks" ~ 22,
                            `Week` == "Gt_23_To_24_Weeks" ~ 23,
                            `Week` == "Gt_24_To_25_Weeks" ~ 24,
                            `Week` == "Gt_25_To_26_Weeks" ~ 25,
                            `Week` == "Gt_26_To_27_Weeks" ~ 26,
                            `Week` == "Gt_27_To_28_Weeks" ~ 27,
                            `Week` == "Gt_28_To_29_Weeks" ~ 28,
                            `Week` == "Gt_29_To_30_Weeks" ~ 29,
                            `Week` == "Gt_30_To_31_Weeks" ~ 30,
                            `Week` == "Gt_31_To_32_Weeks" ~ 31,
                            `Week` == "Gt_32_To_33_Weeks" ~ 32,
                            `Week` == "Gt_33_To_34_Weeks" ~ 33,
                            `Week` == "Gt_34_To_35_Weeks" ~ 34,
                            `Week` == "Gt_35_To_36_Weeks" ~ 35,
                            `Week` == "Gt_36_To_37_Weeks" ~ 36,
                            `Week` == "Gt_37_To_38_Weeks" ~ 37,
                            `Week` == "Gt_38_To_39_Weeks" ~ 38,
                            `Week` == "Gt_39_To_40_Weeks" ~ 39,
                            `Week` == "Gt_40_To_41_Weeks" ~ 40,
                            `Week` == "Gt_41_To_42_Weeks" ~ 41,
                            `Week` == "Gt_42_To_43_Weeks" ~ 42,
                            `Week` == "Gt_43_To_44_Weeks" ~ 43,
                            `Week` == "Gt_44_To_45_Weeks" ~ 44,
                            `Week` == "Gt_45_To_46_Weeks" ~ 45,
                            `Week` == "Gt_46_To_47_Weeks" ~ 46,
                            `Week` == "Gt_47_To_48_Weeks" ~ 47,
                            `Week` == "Gt_48_To_49_Weeks" ~ 48,
                            `Week` == "Gt_49_To_50_Weeks" ~ 49,
                            `Week` == "Gt_50_To_51_Weeks" ~ 50,
                            `Week` == "Gt_51_To_52_Weeks" ~ 51,
                            `Week` == "Gt_52_Weeks" ~ 52,
                            `Week` == "Gt_52_To_53_Weeks" ~ 52,
                            `Week` == "Gt_53_To_54_Weeks" ~ 53,
                            `Week` == "Gt_54_To_55_Weeks" ~ 54,
                            `Week` == "Gt_55_To_56_Weeks" ~ 55,
                            `Week` == "Gt_56_To_57_Weeks" ~ 56,
                            `Week` == "Gt_57_To_58_Weeks" ~ 57,
                            `Week` == "Gt_58_To_59_Weeks" ~ 58,
                            `Week` == "Gt_59_To_60_Weeks" ~ 59,
                            `Week` == "Gt_60_To_61_Weeks" ~ 60,
                            `Week` == "Gt_61_To_62_Weeks" ~ 61,
                            `Week` == "Gt_62_To_63_Weeks" ~ 62,
                            `Week` == "Gt_63_To_64_Weeks" ~ 63,
                            `Week` == "Gt_64_To_65_Weeks" ~ 64,
                            `Week` == "Gt_65_To_66_Weeks" ~ 65,
                            `Week` == "Gt_66_To_67_Weeks" ~ 66,
                            `Week` == "Gt_67_To_68_Weeks" ~ 67,
                            `Week` == "Gt_68_To_69_Weeks" ~ 68,
                            `Week` == "Gt_69_To_70_Weeks" ~ 69,
                            `Week` == "Gt_70_To_71_Weeks" ~ 70,
                            `Week` == "Gt_71_To_72_Weeks" ~ 71,
                            `Week` == "Gt_72_To_73_Weeks" ~ 72,
                            `Week` == "Gt_73_To_74_Weeks" ~ 73,
                            `Week` == "Gt_74_To_75_Weeks" ~ 74,
                            `Week` == "Gt_75_To_76_Weeks" ~ 75,
                            `Week` == "Gt_76_To_77_Weeks" ~ 76,
                            `Week` == "Gt_77_To_78_Weeks" ~ 77,
                            `Week` == "Gt_78_To_79_Weeks" ~ 78,
                            `Week` == "Gt_79_To_80_Weeks" ~ 79,
                            `Week` == "Gt_80_To_81_Weeks" ~ 80,
                            `Week` == "Gt_81_To_82_Weeks" ~ 81,
                            `Week` == "Gt_82_To_83_Weeks" ~ 82,
                            `Week` == "Gt_83_To_84_Weeks" ~ 83,
                            `Week` == "Gt_84_To_85_Weeks" ~ 84,
                            `Week` == "Gt_85_To_86_Weeks" ~ 85,
                            `Week` == "Gt_86_To_87_Weeks" ~ 86,
                            `Week` == "Gt_87_To_88_Weeks" ~ 87,
                            `Week` == "Gt_88_To_89_Weeks" ~ 88,
                            `Week` == "Gt_89_To_90_Weeks" ~ 89,
                            `Week` == "Gt_90_To_91_Weeks" ~ 90,
                            `Week` == "Gt_91_To_92_Weeks" ~ 91,
                            `Week` == "Gt_92_To_93_Weeks" ~ 92,
                            `Week` == "Gt_93_To_94_Weeks" ~ 93,
                            `Week` == "Gt_94_To_95_Weeks" ~ 94,
                            `Week` == "Gt_95_To_96_Weeks" ~ 95,
                            `Week` == "Gt_96_To_97_Weeks" ~ 96,
                            `Week` == "Gt_97_To_98_Weeks" ~ 97,
                            `Week` == "Gt_98_To_99_Weeks" ~ 98,
                            `Week` == "Gt_99_To_100_Weeks" ~ 99,
                            `Week` == "Gt_100_To_101_Weeks" ~ 100,
                            `Week` == "Gt_101_To_102_Weeks" ~ 101,
                            `Week` == "Gt_102_To_103_Weeks" ~ 102,
                            `Week` == "Gt_103_To_104_Weeks" ~ 103,
                            `Week` == "Gt_104_Weeks" ~ 104)) |> 
  select(`StartDate` = `Report_Date`,
         `CommissionerCode` = `Commissioner_Organisation_Code`,
         `ProviderCode` = `Provider_Organisation_Code`,
         `PathwayDescription` = `RTT_Part_Description`,
         `Week`,
         `Waits`) |> 
  mutate(`MonthDate` = floor_date(as.Date(`StartDate`),
                                  "month"),
         `CommissionerCode` = case_when(`CommissionerCode` == "11X" ~ `CommissionerCode`,
                                        TRUE ~ "OTH"),
         `CommissionerDescription` = case_when(`CommissionerCode` == "11X" ~ "Somerset",
                                               TRUE ~ "Other"),
         `ProviderCode` = case_when(`ProviderCode` %in% c("RH5",
                                                          "RBA",
                                                          "RA4") ~ `ProviderCode`,
                                    TRUE ~ "OTH"),
         `ProviderDescription` = case_when(`ProviderCode` %in% c("RH5",
                                                                 "RBA",
                                                                 "RA4") ~ "Somerset",
                                           TRUE ~ "Other"),
         `WeekGrouping1` = case_when(`Week` <= 17 ~ "0-17",
                                     `Week` >= 18 ~ "18+"),
         `WeekGrouping2` = case_when(`Week` <= 51 ~ "0-51",
                                     `Week` <= 64 ~ "52-64",
                                     `Week` <= 77 ~ "65-77",
                                     `Week` <= 103 ~ "78-103",
                                     `Week` >= 104 ~ "104+")) |> 
  group_by(`MonthDate`,
           `CommissionerDescription`,
           `ProviderCode`,
           `ProviderDescription`,
           `PathwayDescription`,
           `WeekGrouping1`,
           `WeekGrouping2`,
           `Week`) |> 
  summarise(`Waits` = sum(`Waits`,
                          na.rm = TRUE)) |> 
  ungroup()